[project]
name = "clothes-failures-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "einops>=0.8.2",
    "kornia>=0.8.2",
    "numpy>=1.26.4,<2.0.0",
    "opencv-python>=4.8.0.00,<4.11",
    "pyinstaller>=6.19.0",
    "pyqt6==6.10.1",
    "python-dotenv==1.2.1",
    "python-snap7>=3.0.0",
    "reportlab==4.4.10",
    "roboflow==1.2.13",
    "timm>=1.0.26",
    "torch>=2.7.0",
    "torchvision>=0.18.0",
    "torchaudio>=2.7.0",
    "transformers>=4.45.0",
    "ultralytics==8.3.241",
    "albumentations>=2.0.8",
    "pandas>=3.0.2",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }

[tool.uv]
index-strategy = "unsafe-best-match"
